## a1816653_ZuxingWu_group34_assign3

In [270]:
# import task2 code which contains task1 code
# %run task2.ipynb
import warnings
warnings.filterwarnings('ignore')

# Data preparation

In [271]:
# fake 20 transactions data with A, B, C, D, E
# A, B, C, D, E are 5 different products
transactions = [
    ['A', 'B', 'C'],
    ['A', 'C', 'D'],
    ['B', 'D'],
    ['A', 'B', 'C', 'E'],
    ['A', 'C', 'D'],
    ['B', 'D'],
    ['A', 'B', 'C'],
    ['A', 'C', 'D', 'E'],
    ['B', 'D'],
    ['A', 'B', 'C'],
    ['A', 'C', 'D'],
    ['B', 'D', 'E'],
    ['A', 'B', 'C'],
    ['A', 'C', 'D'],
    ['B', 'D'],
    ['A', 'B', 'C'],
    ['A', 'C', 'E'],
    ['B', 'D'],
    ['A', 'E', 'C'],
    ['A', 'C', 'D'],
]

# Association pattern mining

In [272]:
# use FP-Growth algorithm to generate association rules
from mlxtend.frequent_patterns import fpgrowth, association_rules
import pandas as pd

# convert transactions to one-hot encoded DataFrame
df = pd.DataFrame(transactions)
df = pd.get_dummies(df.unstack()).groupby(level=1).sum()
df

A  B  C  D  E
0   1  1  1  0  0
1   1  0  1  1  0
2   0  1  0  1  0
3   1  1  1  0  1
4   1  0  1  1  0
5   0  1  0  1  0
6   1  1  1  0  0
7   1  0  1  1  1
8   0  1  0  1  0
9   1  1  1  0  0
10  1  0  1  1  0
11  0  1  0  1  1
12  1  1  1  0  0
13  1  0  1  1  0
14  0  1  0  1  0
15  1  1  1  0  0
16  1  0  1  0  1
17  0  1  0  1  0
18  1  0  1  0  1
19  1  0  1  1  0

In [273]:
# apply FP-Growth algorithm
frequent_itemsets = fpgrowth(df, min_support=0.2, use_colnames=True)

# generate association rules
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.8)
rules

antecedents consequents  antecedent support  consequent support  support   
0          (A)         (C)                0.70                 0.7      0.7  \
1          (C)         (A)                0.70                 0.7      0.7   
2       (A, B)         (C)                0.30                 0.7      0.3   
3       (B, C)         (A)                0.30                 0.7      0.3   
4       (A, D)         (C)                0.30                 0.7      0.3   
5       (C, D)         (A)                0.30                 0.7      0.3   
6          (E)         (A)                0.25                 0.7      0.2   
7          (E)         (C)                0.25                 0.7      0.2   
8       (A, E)         (C)                0.20                 0.7      0.2   
9       (E, C)         (A)                0.20                 0.7      0.2   
10         (E)      (A, C)                0.25                 0.7      0.2   

    confidence      lift  leverage  conviction  zhangs_metric  
0          1.0  1.428571     0.210         inf       1.000000  
1          1.0  1.428571     0.210         inf       1.000000  
2          1.0  1.428571     0.090         inf       0.428571  
3          1.0  1.428571     0.090         inf       0.428571  
4          1.0  1.428571     0.090         inf       0.428571  
5          1.0  1.428571     0.090         inf       0.428571  
6          0.8  1.142857     0.025         1.5       0.166667  
7          0.8  1.142857     0.025         1.5       0.166667  
8          1.0  1.428571     0.060         inf       0.375000  
9          1.0  1.428571     0.060         inf       0.375000  
10         0.8  1.142857     0.025         1.5       0.166667

In [274]:
# use the apriori function to find frequent itemsets
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.8)
rules

antecedents consequents  antecedent support  consequent support  support   
0          (A)         (C)                0.70                 0.7      0.7  \
1          (C)         (A)                0.70                 0.7      0.7   
2          (E)         (A)                0.25                 0.7      0.2   
3          (E)         (C)                0.25                 0.7      0.2   
4       (A, B)         (C)                0.30                 0.7      0.3   
5       (B, C)         (A)                0.30                 0.7      0.3   
6       (A, D)         (C)                0.30                 0.7      0.3   
7       (C, D)         (A)                0.30                 0.7      0.3   
8       (A, E)         (C)                0.20                 0.7      0.2   
9       (E, C)         (A)                0.20                 0.7      0.2   
10         (E)      (A, C)                0.25                 0.7      0.2   

    confidence      lift  leverage  conviction  zhangs_metric  
0          1.0  1.428571     0.210         inf       1.000000  
1          1.0  1.428571     0.210         inf       1.000000  
2          0.8  1.142857     0.025         1.5       0.166667  
3          0.8  1.142857     0.025         1.5       0.166667  
4          1.0  1.428571     0.090         inf       0.428571  
5          1.0  1.428571     0.090         inf       0.428571  
6          1.0  1.428571     0.090         inf       0.428571  
7          1.0  1.428571     0.090         inf       0.428571  
8          1.0  1.428571     0.060         inf       0.375000  
9          1.0  1.428571     0.060         inf       0.375000  
10         0.8  1.142857     0.025         1.5       0.166667

# Collaborative Filtering

In [275]:
import numpy as np
# convert transactions to one-hot encoded DataFrame
df = pd.DataFrame(transactions)
df_transactions = pd.get_dummies(df.unstack()).groupby(level=1).sum()
# array_transactions↓ has no column names, while df_transactions↑ keeps column names
array_transactions = np.array(df_transactions)
array_transactions

array([[1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 1],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 1],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0]])

In [276]:
df_transactions.shape

(20, 5)

In [277]:
def uv_decomposition(R, k, learning_rate, regularization):
    """
    Performs UV decomposition on the input matrix R, with a target rank of k, using stochastic gradient descent (SGD).
    Returns the decomposed matrices U and V.
    """
    # Initialize U and V with random values
    num_users, num_items = R.shape
    U = np.random.rand(num_users, k) #num users by k
    V = np.random.rand(k, num_items) #k by num items

    # Perform stochastic gradient descent to optimize U and V
    for epoch in range(10):
        for i in range(num_users):
            for j in range(num_items):
                if R[i, j] > 0:
                    error = R[i, j] - np.dot(U[i, :], V[:, j])
                    U[i, :] += learning_rate * (error * V[:, j] - regularization * U[i, :])
                    V[:, j] += learning_rate * (error * U[i, :] - regularization * V[:, j])

    # Return the decomposed matrices U and V
    return U, V

In [278]:
# pick the bset K for UV decomposition
def calculate_rmse(R, U, V):
    predicted_R = np.dot(U, V)
    error = R - predicted_R
    error = error[R > 0]  # Only consider known values
    return np.sqrt(np.mean(error**2))

# Split the data into training and validation sets

best_k = None
best_rmse = float('inf')

for k in range(1, 10):
    U, V = uv_decomposition(array_transactions, k, 0.1, 0.1)
    rmse = calculate_rmse(array_transactions, U, V)
    print(f"k={k}, RMSE={rmse}")
    if rmse < best_rmse:
        best_rmse = rmse
        best_k = k

print(f"Best k: {best_k} with RMSE: {best_rmse}")

k=1, RMSE=0.11021214343933088
k=2, RMSE=0.11060550549917628
k=3, RMSE=0.10244171130741235
k=4, RMSE=0.09568334764718636
k=5, RMSE=0.0983324313829675
k=6, RMSE=0.09561111839742044
k=7, RMSE=0.10126061934381395
k=8, RMSE=0.09117096680960284
k=9, RMSE=0.08564478877330992
Best k: 9 with RMSE: 0.08564478877330992


In [279]:
# perform UV decomposition on the user-good matrix
U, V = uv_decomposition(array_transactions, best_k, 0.1, 0.1)

# calculate the interest of users in goods
user_ratings = np.dot(U, V)

# discard ratings of bought items
user_ratings[array_transactions > 0] = 0.0
# print("Original user-good matrix:")
# print(df_transactions)
print("user_ratings:")
print(user_ratings)

user_ratings:
[[0.         0.         0.         0.98656023 0.95988023]
 [0.         0.82314281 0.         0.         0.91378968]
 [0.95574909 0.         0.98545524 0.         1.02484148]
 [0.         0.         0.         0.96543141 0.        ]
 [0.         0.81853572 0.         0.         0.8486971 ]
 [0.91725045 0.         0.9152185  0.         0.95268253]
 [0.         0.         0.         0.91670105 1.13533165]
 [0.         0.71190068 0.         0.         0.        ]
 [0.68336353 0.         0.76038692 0.         0.85841341]
 [0.         0.         0.         0.83774917 0.94873534]
 [0.         0.89421372 0.         0.         1.02495591]
 [0.87724238 0.         0.91979116 0.         0.        ]
 [0.         0.         0.         0.83840164 0.80064009]
 [0.         0.8297876  0.         0.         0.96804149]
 [0.99295918 0.         1.04365369 0.         0.99252902]
 [0.         0.         0.         0.90974652 1.04829838]
 [0.         0.80835682 0.         0.87946935 0.        ]


### remove bought items

In [280]:
# get the recommendation order for each user
print(np.argsort(-user_ratings))

[[3 4 0 1 2]
 [4 1 0 2 3]
 [4 2 0 1 3]
 [3 0 1 2 4]
 [4 1 0 2 3]
 [4 0 2 1 3]
 [4 3 0 1 2]
 [1 0 2 3 4]
 [4 2 0 1 3]
 [4 3 0 1 2]
 [4 1 0 2 3]
 [2 0 1 3 4]
 [3 4 0 1 2]
 [4 1 0 2 3]
 [2 0 4 1 3]
 [4 3 0 1 2]
 [3 1 0 2 4]
 [4 2 0 1 3]
 [3 1 0 2 4]
 [1 4 0 2 3]]


By combining collaborative filtering with association rule mining, we can leverage both user-specific preferences and item relationships to create a more robust recommendation system. Collaborative filtering provides personalized recommendations based on user behavior, while association rule mining uncovers hidden patterns and relationships between items. This hybrid approach can enhance recommendation quality and diversify the suggestions provided to users.

# Simple Combination

In [281]:
# combine collaborative filtering and association rules to recommend goods to users
def combine_recommendations(ar_recommendations, cf_recommendations, weight_cf=0.5, weight_ar=0.5):
    combined_scores = {}
    for item in cf_recommendations:
        combined_scores[item] = weight_cf * cf_recommendations[item]
    for item in ar_recommendations:
        if item in combined_scores:
            combined_scores[item] += weight_ar * ar_recommendations[item]
        else:
            combined_scores[item] = weight_ar * ar_recommendations[item]
            
    combined_sorted = sorted(combined_scores.items(), key=lambda x: x[1], reverse=True)
    print("combined_sorted: ", combined_sorted)
    return [item for item, score in combined_sorted]

In [282]:
# test combine_recommendations function
ar_recommendations = {'A': 0.5, 'B': 0.3, 'C': 0.2, 'E': 0.1}
cf_recommendations = {'A': 0.1, 'B': 0.2, 'C': 0.3, 'D': 0.9}
combine_recommendations(ar_recommendations, cf_recommendations, 0.5, 0.5)

combined_sorted:  [('D', 0.45), ('A', 0.3), ('B', 0.25), ('C', 0.25), ('E', 0.05)]


['D', 'A', 'B', 'C', 'E']

# Genetic algorithm

Sometimes, the user gets bored with recommendations which are similar to their profiles, which leads to the over-specialization problem. Over-specialization is caused by limited content data, under which content-based recommendation algorithms suggest goods directly related to the customer profile rather than new things.  
In order to recommend novel and serendipitous items along with familiar items, we need to use genetic algorithm that brings diversity to recommendations and efficiently adjust and suggest unpredictable and innovative things to the user.

In [284]:
import random

# get initial population function
def get_initial_chromosome(array_transactions):
    chromosome = [random.choice([0, 1]) for _ in range(array_transactions.shape[0] * array_transactions.shape[1])]
    # iterate over array_transactions and set value=1 items to 0
    for i in range(array_transactions.shape[0]):
        for j in range(array_transactions.shape[1]):
            if array_transactions[i, j] > 0:
                chromosome[i * array_transactions.shape[1] + j] = 0
    # print(chromosome)
    return chromosome

In [ ]:
# define the fitness function
def fitness(recommendations, array_transactions):
    fitness = 0
    for (user_idx, good_idx), interest in recommendations.items():
        # only consider goods that the user has not bought
        if array_transactions[user_idx, good_idx] == 0:
            fitness += interest
    return fitness

In [285]:
# use genetic algorithm to generate recommendations

# define the genetic algorithm
def genetic_algorithm(array_transactions, num_generations, population_size, mutation_rate):
    # apply UV decomposition
    # U, V = uv_decomposition(array_transactions, best_k, 0.1, 0.1)

    # calculate the interest of users in goods
    # user_ratings = np.dot(U, V)

    # generate recommendations using the user_ratings matrix
    def generate_recommendations(user_ratings):
        recommendations = {}
        for user_idx, user_interest in enumerate(user_ratings):
            for good_idx, interest in enumerate(user_interest):
                if array_transactions[user_idx, good_idx] == 0:
                    # print("user_idx: ", user_idx, "good_idx: ", good_idx, "interest: ", interest)
                    recommendations[(user_idx, good_idx)] = interest
        return recommendations

    # generate recommendations
    recommendations = generate_recommendations(user_ratings)

    # initialize the population
    population = []
    top_population = []
    for _ in range(population_size):
        # generate a random chromosome
        chromosome = get_initial_chromosome(array_transactions)
        population.append(chromosome)

    # evolve the population
    for generation in range(num_generations):
        # evaluate the fitness of each chromosome
        fitnesses = []
        for chromosome in population:
            recommendations = {}
            for i, value in enumerate(chromosome):
                user_idx = i // array_transactions.shape[1]
                item_idx = i % array_transactions.shape[1]
                if value == 1 and user_ratings[user_idx, item_idx] > 0.0:
                    recommendations[(user_idx, item_idx)] = user_ratings[user_idx, item_idx]
            fitnesses.append(fitness(recommendations, array_transactions))

        # select the top chromosomes
        top_population = [population[i] for i in np.argsort(fitnesses)[-population_size:]]

        # create the next generation
        new_population = []
        for _ in range(population_size):
            # pick the best two as parents
            parent1 = top_population[-1]
            parent2 = top_population[-2]
            # parent1 = random.choice(top_population)
            # parent2 = random.choice(top_population)
            child = []
            for i in range(len(parent1)):
                if random.random() < mutation_rate:
                    child.append(random.choice([parent1[i], parent2[i]]))
                else:
                    child.append(parent1[i])
            new_population.append(child)
        population = new_population

    return top_population

In [294]:
top_population = genetic_algorithm(array_transactions, 100, 10, 0.5)
print(top_population[0])

[0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1]


In [295]:
# apply the genetic algorithm
for chromosome in top_population:
    recommendations = {}
    for i, value in enumerate(chromosome):
        user_idx = i // df_transactions.shape[1]
        item_idx = i % df_transactions.shape[1]
        if value == 1:
            recommendations[(user_idx, item_idx)] = user_ratings[user_idx, item_idx]
    print("Recommendations:")
    print(recommendations)
    print("Fitness:")
    print(fitness(recommendations, array_transactions))
# print(top_population[0])

Recommendations:
{(0, 3): 0.9865602313938119, (0, 4): 0.9598802337835317, (1, 1): 0.823142810199983, (1, 4): 0.913789679593058, (2, 0): 0.9557490922175423, (2, 2): 0.9854552441187435, (2, 4): 1.024841482057372, (3, 3): 0.9654314104482004, (4, 1): 0.818535722067531, (4, 4): 0.8486971033362433, (5, 0): 0.9172504549767618, (5, 2): 0.915218498358722, (5, 4): 0.9526825301598054, (6, 4): 1.1353316541714915, (8, 2): 0.760386915177791, (9, 3): 0.8377491659690421, (9, 4): 0.948735336700432, (10, 1): 0.8942137193833783, (10, 4): 1.024955906878052, (11, 0): 0.8772423783791932, (11, 2): 0.9197911624902043, (12, 3): 0.8384016424413344, (12, 4): 0.8006400856610822, (13, 1): 0.8297875958162686, (15, 3): 0.9097465235148476, (15, 4): 1.0482983755456665, (16, 3): 0.879469348783164, (17, 0): 1.0006707022619374, (17, 2): 1.0152692375325323, (17, 4): 1.0749435174228281, (18, 1): 0.8964660834969284, (18, 3): 0.9012602050513892, (19, 1): 0.9967551185467384, (19, 4): 0.9718185361688892}
Fitness:
31.6291677041

# References

Parvatikar, S & Joshi, B 2015, ‘Online book recommendation system by using collaborative filtering and association mining’, in *2015 IEEE International Conference on Computational Intelligence and Computing Research (ICCIC)*, IEEE, pp. 1–4.

Stitini, O., Kaloun, S., Bencharef, O. An Improved Recommender System Solution to Mitigate the Over-Specialization Problem Using Genetic Algorithms. *Electronics* 2022,11,242. https:// doi.org/10.3390/electronics11020242