## a1816653_ZuxingWu_group34_assign3

In [30]:
# import task2 code which contains task1 code
# %run task2.ipynb
import warnings
warnings.filterwarnings('ignore')

# Data preparation

In [31]:
# fake 20 transactions data with A, B, C, D, E
# A, B, C, D, E are 5 different products
transactions = [
    ['A', 'B', 'C'],
    ['A', 'C', 'D'],
    ['B', 'D'],
    ['A', 'B', 'C', 'E'],
    ['A', 'C', 'D'],
    ['B', 'D'],
    ['A', 'B', 'C'],
    ['A', 'C', 'D', 'E'],
    ['B', 'D'],
    ['A', 'B', 'C'],
    ['A', 'C', 'D'],
    ['B', 'D', 'E'],
    ['A', 'B', 'C'],
    ['A', 'C', 'D'],
    ['B', 'D'],
    ['A', 'B', 'C'],
    ['A', 'C', 'E'],
    ['B', 'D'],
    ['A', 'E', 'C'],
    ['A', 'C', 'D'],
]

# Association pattern mining

In [32]:
# use FP-Growth algorithm to generate association rules
from mlxtend.frequent_patterns import fpgrowth, association_rules
import pandas as pd

# convert transactions to one-hot encoded DataFrame
df = pd.DataFrame(transactions)
df = pd.get_dummies(df.unstack()).groupby(level=1).sum()
df

A  B  C  D  E
0   1  1  1  0  0
1   1  0  1  1  0
2   0  1  0  1  0
3   1  1  1  0  1
4   1  0  1  1  0
5   0  1  0  1  0
6   1  1  1  0  0
7   1  0  1  1  1
8   0  1  0  1  0
9   1  1  1  0  0
10  1  0  1  1  0
11  0  1  0  1  1
12  1  1  1  0  0
13  1  0  1  1  0
14  0  1  0  1  0
15  1  1  1  0  0
16  1  0  1  0  1
17  0  1  0  1  0
18  1  0  1  0  1
19  1  0  1  1  0

In [33]:
# apply FP-Growth algorithm
frequent_itemsets = fpgrowth(df, min_support=0.2, use_colnames=True)

# generate association rules
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.8)
rules

antecedents consequents  antecedent support  consequent support  support   
0          (C)         (A)                0.70                 0.7      0.7  \
1          (A)         (C)                0.70                 0.7      0.7   
2       (C, B)         (A)                0.30                 0.7      0.3   
3       (A, B)         (C)                0.30                 0.7      0.3   
4       (C, D)         (A)                0.30                 0.7      0.3   
5       (A, D)         (C)                0.30                 0.7      0.3   
6          (E)         (A)                0.25                 0.7      0.2   
7          (E)         (C)                0.25                 0.7      0.2   
8       (C, E)         (A)                0.20                 0.7      0.2   
9       (E, A)         (C)                0.20                 0.7      0.2   
10         (E)      (C, A)                0.25                 0.7      0.2   

    confidence      lift  leverage  conviction  zhangs_metric  
0          1.0  1.428571     0.210         inf       1.000000  
1          1.0  1.428571     0.210         inf       1.000000  
2          1.0  1.428571     0.090         inf       0.428571  
3          1.0  1.428571     0.090         inf       0.428571  
4          1.0  1.428571     0.090         inf       0.428571  
5          1.0  1.428571     0.090         inf       0.428571  
6          0.8  1.142857     0.025         1.5       0.166667  
7          0.8  1.142857     0.025         1.5       0.166667  
8          1.0  1.428571     0.060         inf       0.375000  
9          1.0  1.428571     0.060         inf       0.375000  
10         0.8  1.142857     0.025         1.5       0.166667

In [34]:
# use the apriori function to find frequent itemsets
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.8)
rules

antecedents consequents  antecedent support  consequent support  support   
0          (C)         (A)                0.70                 0.7      0.7  \
1          (A)         (C)                0.70                 0.7      0.7   
2          (E)         (A)                0.25                 0.7      0.2   
3          (E)         (C)                0.25                 0.7      0.2   
4       (C, B)         (A)                0.30                 0.7      0.3   
5       (A, B)         (C)                0.30                 0.7      0.3   
6       (C, D)         (A)                0.30                 0.7      0.3   
7       (A, D)         (C)                0.30                 0.7      0.3   
8       (C, E)         (A)                0.20                 0.7      0.2   
9       (E, A)         (C)                0.20                 0.7      0.2   
10         (E)      (C, A)                0.25                 0.7      0.2   

    confidence      lift  leverage  conviction  zhangs_metric  
0          1.0  1.428571     0.210         inf       1.000000  
1          1.0  1.428571     0.210         inf       1.000000  
2          0.8  1.142857     0.025         1.5       0.166667  
3          0.8  1.142857     0.025         1.5       0.166667  
4          1.0  1.428571     0.090         inf       0.428571  
5          1.0  1.428571     0.090         inf       0.428571  
6          1.0  1.428571     0.090         inf       0.428571  
7          1.0  1.428571     0.090         inf       0.428571  
8          1.0  1.428571     0.060         inf       0.375000  
9          1.0  1.428571     0.060         inf       0.375000  
10         0.8  1.142857     0.025         1.5       0.166667

# Collaborative Filtering

In [35]:
import numpy as np
# convert transactions to one-hot encoded DataFrame
df = pd.DataFrame(transactions)
df_transactions = pd.get_dummies(df.unstack()).groupby(level=1).sum()
# array_transactions↓ has no column names, while df_transactions↑ keeps column names
array_transactions = np.array(df_transactions)
array_transactions

array([[1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 1],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 1],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0]])

In [62]:
df_transactions.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [63]:
df_transactions.index

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype='int64')

In [36]:
df_transactions.shape

(20, 5)

In [37]:
def uv_decomposition(R, k, learning_rate, regularization):
    """
    Performs UV decomposition on the input matrix R, with a target rank of k, using stochastic gradient descent (SGD).
    Returns the decomposed matrices U and V.
    """
    # Initialize U and V with random values
    num_users, num_items = R.shape
    U = np.random.rand(num_users, k) #num users by k
    V = np.random.rand(k, num_items) #k by num items

    # Perform stochastic gradient descent to optimize U and V
    for epoch in range(10):
        for i in range(num_users):
            for j in range(num_items):
                if R[i, j] > 0:
                    error = R[i, j] - np.dot(U[i, :], V[:, j])
                    U[i, :] += learning_rate * (error * V[:, j] - regularization * U[i, :])
                    V[:, j] += learning_rate * (error * U[i, :] - regularization * V[:, j])

    # Return the decomposed matrices U and V
    return U, V

In [38]:
# pick the bset K for UV decomposition
def calculate_rmse(R, U, V):
    predicted_R = np.dot(U, V)
    error = R - predicted_R
    error = error[R > 0]  # Only consider known values
    return np.sqrt(np.mean(error**2))

# Split the data into training and validation sets

best_k = None
best_rmse = float('inf')

for k in range(1, 10):
    U, V = uv_decomposition(array_transactions, k, 0.1, 0.1)
    rmse = calculate_rmse(array_transactions, U, V)
    print(f"k={k}, RMSE={rmse}")
    if rmse < best_rmse:
        best_rmse = rmse
        best_k = k

print(f"Best k: {best_k} with RMSE: {best_rmse}")

k=1, RMSE=0.11151133060035234
k=2, RMSE=0.10764774696815373
k=3, RMSE=0.10647101375302316
k=4, RMSE=0.09528242136170542
k=5, RMSE=0.0973402834296561
k=6, RMSE=0.10293921093956508
k=7, RMSE=0.09256551230837444
k=8, RMSE=0.0982423549356177
k=9, RMSE=0.1016468910819456
Best k: 7 with RMSE: 0.09256551230837444


In [39]:
# perform UV decomposition on the user-good matrix
U, V = uv_decomposition(array_transactions, best_k, 0.1, 0.1)

# calculate the interest of users in goods
user_ratings = np.dot(U, V)

# discard ratings of bought items
user_ratings[array_transactions > 0] = 0.0
# print("Original user-good matrix:")
# print(df_transactions)
print("user_ratings:")
print(user_ratings)

user_ratings:
[[0.         0.         0.         0.9005926  0.84904115]
 [0.         0.89852157 0.         0.         0.86975037]
 [0.81343826 0.         0.81683778 0.         0.9237753 ]
 [0.         0.         0.         0.85122417 0.        ]
 [0.         0.87542149 0.         0.         0.7453365 ]
 [0.85121989 0.         0.81805316 0.         0.75052894]
 [0.         0.         0.         0.77060622 0.86452642]
 [0.         0.96905235 0.         0.         0.        ]
 [0.89477675 0.         0.87447752 0.         0.73800754]
 [0.         0.         0.         0.95509821 0.90370796]
 [0.         0.96225754 0.         0.         0.93323134]
 [0.81207658 0.         0.82834906 0.         0.        ]
 [0.         0.         0.         0.90459467 0.89075182]
 [0.         0.90650879 0.         0.         0.94736572]
 [0.94396085 0.         0.99847198 0.         1.00958717]
 [0.         0.         0.         0.95911622 0.84634501]
 [0.         0.99619003 0.         0.96798969 0.        ]


### remove bought items

In [40]:
# get the recommendation order for each user
print(np.argsort(-user_ratings))

[[3 4 0 1 2]
 [1 4 0 2 3]
 [4 2 0 1 3]
 [3 0 1 2 4]
 [1 4 0 2 3]
 [0 2 4 1 3]
 [4 3 0 1 2]
 [1 0 2 3 4]
 [0 2 4 1 3]
 [3 4 0 1 2]
 [1 4 0 2 3]
 [2 0 1 3 4]
 [3 4 0 1 2]
 [4 1 0 2 3]
 [4 2 0 1 3]
 [3 4 0 1 2]
 [1 3 0 2 4]
 [4 2 0 1 3]
 [3 1 0 2 4]
 [1 4 0 2 3]]


By combining collaborative filtering with association rule mining, we can leverage both user-specific preferences and item relationships to create a more robust recommendation system. Collaborative filtering provides personalized recommendations based on user behavior, while association rule mining uncovers hidden patterns and relationships between items. This hybrid approach can enhance recommendation quality and diversify the suggestions provided to users.

# Simple Combination

In [41]:
# combine association results and collaborative filtering ratings to recommend
def combine_recommendations(predicted_items, uv_top5):
    """
    if the item is in the top 5 of the UV_top5, then recommend it
    if no items are in the top 5 of the UV_top5, then recommend the top 1
    """
    recommendations = []
    # sort top5 by its ratings
    uv_top5 = dict(sorted(uv_top5.items(), key=lambda x: x[1], reverse=True))
    recommendations.append([item for item in uv_top5.keys() if item in predicted_items])
    if len(recommendations[0]) == 0:
        recommendations[0].append(list(uv_top5.keys())[0])

    return recommendations

In [42]:
# test combine_recommendations function
predicted_items = ['A', 'B', 'C', 'E']
uv_top5 = {'A': 0.1, 'B': 0.2, 'C': 0.3, 'D': 0.9}
combine_recommendations(predicted_items, uv_top5)

[['C', 'B', 'A']]

# Genetic algorithm

Sometimes, the user gets bored with recommendations which are similar to their profiles, which leads to the over-specialization problem. Over-specialization is caused by limited content data, under which content-based recommendation algorithms suggest goods directly related to the customer profile rather than new things.  
In order to recommend novel and serendipitous items along with familiar items, we need to use genetic algorithm that brings diversity to recommendations and efficiently adjust and suggest unpredictable and innovative things to the user.

In [43]:
import random

# get initial population function
def get_initial_chromosome(array_transactions):
    chromosome = [random.choice([0, 1]) for _ in range(array_transactions.shape[0] * array_transactions.shape[1])]
    # iterate over array_transactions and set value=1 items to 0
    for i in range(array_transactions.shape[0]):
        for j in range(array_transactions.shape[1]):
            # if the item is bought, set it to 0, do not recommend it
            if array_transactions[i, j] > 0:
                chromosome[i * array_transactions.shape[1] + j] = 0
    # print(chromosome)
    return chromosome

In [44]:
# define the fitness function, sum the total interest of recommended items of all users
def fitness(recommendations, array_transactions):
    fitness = 0
    for (user_idx, good_idx), interest in recommendations.items():
        # only consider goods that the user has not bought
        if array_transactions[user_idx, good_idx] == 0:
            fitness += interest
    return fitness

In [51]:
# use genetic algorithm to generate recommendations

# define the genetic algorithm
def genetic_algorithm(array_transactions, num_generations, population_size, mutation_rate):
    # initialize the population
    population = []
    top_population = []
    for _ in range(population_size):
        # generate a random chromosome
        chromosome = get_initial_chromosome(array_transactions)
        population.append(chromosome)

    # evolve the population
    for generation in range(num_generations):
        # evaluate the fitness of each chromosome
        fitnesses = []
        for chromosome in population:
            recommendations = {}
            for i, value in enumerate(chromosome):
                user_idx = i // array_transactions.shape[1]
                item_idx = i % array_transactions.shape[1]
                if value == 1 and user_ratings[user_idx, item_idx] > 0.0:
                    recommendations[(user_idx, item_idx)] = user_ratings[user_idx, item_idx]
            fitnesses.append(fitness(recommendations, array_transactions))

        # select the top chromosomes
        top_population = [population[i] for i in np.argsort(fitnesses)[-population_size:]]

        # create the next generation
        new_population = []
        for _ in range(population_size):
            # pick the best 2 as parents
            parent1 = top_population[-1]
            parent2 = top_population[-2]
            child = []
            for i in range(len(parent1)):
                if random.random() < mutation_rate:
                    child.append(random.choice([parent1[i], parent2[i]]))
                else:
                    child.append(parent1[i])
            new_population.append(child)
        population = new_population

    return top_population

In [56]:
# apply the genetic algorithm
top_population = genetic_algorithm(array_transactions, 100, 10, 0.5)
print(top_population[-1])

[0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1]


In [64]:
df_transactions.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [65]:
df_transactions.index

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype='int64')

In [67]:
# Get the best recommendation with the highest fitness
best_recommendation = top_population[-1]
# put the recommendation into a DataFrame
recommendations = pd.DataFrame(np.array(best_recommendation).reshape(df_transactions.shape), columns=df_transactions.columns, index=df_transactions.index)
recommendations

A  B  C  D  E
0   0  0  0  1  1
1   0  0  0  0  1
2   1  0  1  0  1
3   0  0  0  1  0
4   0  1  0  0  1
5   1  0  1  0  1
6   0  0  0  0  1
7   0  1  0  0  0
8   0  0  1  0  1
9   0  0  0  1  1
10  0  0  0  0  0
11  1  0  0  0  0
12  0  0  0  1  0
13  0  1  0  0  1
14  1  0  1  0  1
15  0  0  0  0  0
16  0  0  0  1  0
17  1  0  1  0  1
18  0  1  0  1  0
19  0  1  0  0  1

In [53]:
# apply the genetic algorithm
for chromosome in top_population:
    recommendations = {}
    for i, value in enumerate(chromosome):
        user_idx = i // df_transactions.shape[1]
        item_idx = i % df_transactions.shape[1]
        if value == 1:
            recommendations[(user_idx, item_idx)] = user_ratings[user_idx, item_idx]
    print("Recommendations:")
    print(recommendations)
    print("Fitness:")
    print(fitness(recommendations, array_transactions))
# print(top_population[0])

Recommendations:
{(0, 3): 0.9005926039858859, (1, 1): 0.8985215711323934, (1, 4): 0.8697503675462132, (2, 0): 0.8134382614158495, (2, 2): 0.816837777663903, (2, 4): 0.9237753039156555, (3, 3): 0.851224173787986, (4, 4): 0.7453365034734182, (5, 0): 0.851219892688082, (5, 4): 0.7505289401921861, (6, 3): 0.7706062171345867, (6, 4): 0.8645264165142781, (8, 0): 0.8947767517292861, (8, 2): 0.8744775239632062, (8, 4): 0.7380075435464996, (10, 1): 0.9622575383494767, (10, 4): 0.9332313393259781, (11, 2): 0.8283490643923249, (12, 3): 0.9045946722488187, (14, 2): 0.9984719762480143, (14, 4): 1.0095871686107858, (15, 3): 0.9591162165679163, (15, 4): 0.8463450112443428, (16, 1): 0.9961900260811799, (16, 3): 0.967989685377666, (17, 0): 0.8095717920293812, (17, 2): 0.8285515791710673, (17, 4): 0.9603756128024353, (18, 1): 0.9508146196973967, (18, 3): 0.9776657892984502, (19, 1): 0.9812289106749174}
Fitness:
27.477960850809577
Recommendations:
{(0, 3): 0.9005926039858859, (1, 1): 0.8985215711323934, 

# References

Parvatikar, S & Joshi, B 2015, ‘Online book recommendation system by using collaborative filtering and association mining’, in *2015 IEEE International Conference on Computational Intelligence and Computing Research (ICCIC)*, IEEE, pp. 1–4.

Stitini, O., Kaloun, S., Bencharef, O. An Improved Recommender System Solution to Mitigate the Over-Specialization Problem Using Genetic Algorithms. *Electronics* 2022,11,242. https:// doi.org/10.3390/electronics11020242