## a1816653_ZuxingWu_group34_assign3

In [134]:
# import task2 code which contains task1 code
# %run task2.ipynb
import warnings
warnings.filterwarnings('ignore')

# Data preparation

In [135]:
# fake 20 transactions data with A, B, C, D, E
# A, B, C, D, E are 5 different products
transactions = [
    ['A', 'B', 'C'],
    ['A', 'C', 'D'],
    ['B', 'D'],
    ['A', 'B', 'C', 'E'],
    ['A', 'C', 'D'],
    ['B', 'D'],
    ['A', 'B', 'C'],
    ['A', 'C', 'D', 'E'],
    ['B', 'D'],
    ['A', 'B', 'C'],
    ['A', 'C', 'D'],
    ['B', 'D', 'E'],
    ['A', 'B', 'C'],
    ['A', 'C', 'D'],
    ['B', 'D'],
    ['A', 'B', 'C'],
    ['A', 'C', 'E'],
    ['B', 'D'],
    ['A', 'E', 'C'],
    ['A', 'C', 'D'],
]

# Association pattern mining

In [136]:
# use FP-Growth algorithm to generate association rules
from mlxtend.frequent_patterns import fpgrowth, association_rules
import pandas as pd

# convert transactions to one-hot encoded DataFrame
df = pd.DataFrame(transactions)
df = pd.get_dummies(df.unstack()).groupby(level=1).sum()
df

A  B  C  D  E
0   1  1  1  0  0
1   1  0  1  1  0
2   0  1  0  1  0
3   1  1  1  0  1
4   1  0  1  1  0
5   0  1  0  1  0
6   1  1  1  0  0
7   1  0  1  1  1
8   0  1  0  1  0
9   1  1  1  0  0
10  1  0  1  1  0
11  0  1  0  1  1
12  1  1  1  0  0
13  1  0  1  1  0
14  0  1  0  1  0
15  1  1  1  0  0
16  1  0  1  0  1
17  0  1  0  1  0
18  1  0  1  0  1
19  1  0  1  1  0

In [137]:
# apply FP-Growth algorithm
frequent_itemsets = fpgrowth(df, min_support=0.2, use_colnames=True)

# generate association rules
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.8)
rules

antecedents consequents  antecedent support  consequent support  support   
0          (C)         (A)                0.70                 0.7      0.7  \
1          (A)         (C)                0.70                 0.7      0.7   
2       (C, B)         (A)                0.30                 0.7      0.3   
3       (A, B)         (C)                0.30                 0.7      0.3   
4       (C, D)         (A)                0.30                 0.7      0.3   
5       (D, A)         (C)                0.30                 0.7      0.3   
6          (E)         (A)                0.25                 0.7      0.2   
7          (E)         (C)                0.25                 0.7      0.2   
8       (C, E)         (A)                0.20                 0.7      0.2   
9       (E, A)         (C)                0.20                 0.7      0.2   
10         (E)      (C, A)                0.25                 0.7      0.2   

    confidence      lift  leverage  conviction  zhangs_metric  
0          1.0  1.428571     0.210         inf       1.000000  
1          1.0  1.428571     0.210         inf       1.000000  
2          1.0  1.428571     0.090         inf       0.428571  
3          1.0  1.428571     0.090         inf       0.428571  
4          1.0  1.428571     0.090         inf       0.428571  
5          1.0  1.428571     0.090         inf       0.428571  
6          0.8  1.142857     0.025         1.5       0.166667  
7          0.8  1.142857     0.025         1.5       0.166667  
8          1.0  1.428571     0.060         inf       0.375000  
9          1.0  1.428571     0.060         inf       0.375000  
10         0.8  1.142857     0.025         1.5       0.166667

In [138]:
# use the apriori function to find frequent itemsets
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.8)
rules

antecedents consequents  antecedent support  consequent support  support   
0          (C)         (A)                0.70                 0.7      0.7  \
1          (A)         (C)                0.70                 0.7      0.7   
2          (E)         (A)                0.25                 0.7      0.2   
3          (E)         (C)                0.25                 0.7      0.2   
4       (C, B)         (A)                0.30                 0.7      0.3   
5       (A, B)         (C)                0.30                 0.7      0.3   
6       (C, D)         (A)                0.30                 0.7      0.3   
7       (D, A)         (C)                0.30                 0.7      0.3   
8       (C, E)         (A)                0.20                 0.7      0.2   
9       (E, A)         (C)                0.20                 0.7      0.2   
10         (E)      (C, A)                0.25                 0.7      0.2   

    confidence      lift  leverage  conviction  zhangs_metric  
0          1.0  1.428571     0.210         inf       1.000000  
1          1.0  1.428571     0.210         inf       1.000000  
2          0.8  1.142857     0.025         1.5       0.166667  
3          0.8  1.142857     0.025         1.5       0.166667  
4          1.0  1.428571     0.090         inf       0.428571  
5          1.0  1.428571     0.090         inf       0.428571  
6          1.0  1.428571     0.090         inf       0.428571  
7          1.0  1.428571     0.090         inf       0.428571  
8          1.0  1.428571     0.060         inf       0.375000  
9          1.0  1.428571     0.060         inf       0.375000  
10         0.8  1.142857     0.025         1.5       0.166667

# Collaborative Filtering

In [139]:
import numpy as np
# convert transactions to one-hot encoded DataFrame
df = pd.DataFrame(transactions)
df_transactions = pd.get_dummies(df.unstack()).groupby(level=1).sum()
df_transactions = np.array(df_transactions)
df_transactions

array([[1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 1],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 1],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0]])

In [140]:
df_transactions.shape

(20, 5)

In [141]:
def uv_decomposition(R, k, learning_rate, regularization):
    """
    Performs UV decomposition on the input matrix R, with a target rank of k, using stochastic gradient descent (SGD).
    Returns the decomposed matrices U and V.
    """
    # Initialize U and V with random values
    num_users, num_items = R.shape
    U = np.random.rand(num_users, k) #num users by k
    V = np.random.rand(k, num_items) #k by num items

    # Perform stochastic gradient descent to optimize U and V
    for epoch in range(10):
        for i in range(num_users):
            for j in range(num_items):
                if R[i, j] > 0:
                    error = R[i, j] - np.dot(U[i, :], V[:, j])
                    U[i, :] += learning_rate * (error * V[:, j] - regularization * U[i, :])
                    V[:, j] += learning_rate * (error * U[i, :] - regularization * V[:, j])

    # Return the decomposed matrices U and V
    return U, V

In [142]:
# pick the bset K for UV decomposition
def calculate_rmse(R, U, V):
    predicted_R = np.dot(U, V)
    error = R - predicted_R
    error = error[R > 0]  # Only consider known values
    return np.sqrt(np.mean(error**2))

# Split the data into training and validation sets

best_k = None
best_rmse = float('inf')

for k in range(1, 10):
    U, V = uv_decomposition(df_transactions, k, 0.1, 0.1)
    rmse = calculate_rmse(df_transactions, U, V)
    print(f"k={k}, RMSE={rmse}")
    if rmse < best_rmse:
        best_rmse = rmse
        best_k = k

print(f"Best k: {best_k} with RMSE: {best_rmse}")

k=1, RMSE=0.11083952458321908
k=2, RMSE=0.10866165625615612
k=3, RMSE=0.10502171140761002
k=4, RMSE=0.10107827659212788
k=5, RMSE=0.10185594094325982
k=6, RMSE=0.09258837835670483
k=7, RMSE=0.09763524264546838
k=8, RMSE=0.09496338872577668
k=9, RMSE=0.09053870707207325
Best k: 9 with RMSE: 0.09053870707207325


In [143]:
# perform UV decomposition on the user-good matrix
U, V = uv_decomposition(df_transactions, best_k, 0.1, 0.1)

# calculate the interest of users in goods
user_ratings = np.dot(U, V)

# print("Original user-good matrix:")
# print(df_transactions)
print("user_ratings:")
print(user_ratings)

user_ratings:
[[0.84024631 0.91494648 0.85625807 0.80520551 0.95188193]
 [0.90848088 0.79022209 0.90617389 0.89924641 0.87117459]
 [0.89170342 0.87827797 0.91286345 0.85642807 1.03480625]
 [0.84311687 0.80072362 0.8385469  0.7890936  0.94961043]
 [0.89473397 0.8718493  0.92435265 0.89090094 1.04310172]
 [0.97950388 0.92052506 0.97279896 0.95381522 1.05077726]
 [0.91573574 0.92491485 0.92133693 0.92398715 0.98877601]
 [0.84584555 0.73911481 0.87986401 0.90619733 0.87014781]
 [0.93272082 0.92008089 0.95907665 0.96400987 0.92870898]
 [0.95110385 0.87976851 0.8993517  0.92092894 1.09372832]
 [0.87755547 0.81667401 0.9142447  0.91814661 0.80510563]
 [0.92285285 0.89442405 0.95065145 0.91596198 0.87988396]
 [0.95303954 0.92006388 0.97140858 0.99398549 1.02814257]
 [0.96681133 0.94019571 0.95537244 0.91671961 1.12291094]
 [1.02480053 0.97212616 0.95171353 0.93960281 1.28009898]
 [0.97232464 0.9072338  0.96622078 0.92095543 0.96322982]
 [0.90092292 0.85755385 0.9273011  0.95468401 0.94495249]


remove bought items

In [144]:
# get the recommendation order for each user
print(np.argsort(-user_ratings))

[[4 1 2 0 3]
 [0 2 3 4 1]
 [4 2 0 1 3]
 [4 0 2 1 3]
 [4 2 0 3 1]
 [4 0 2 3 1]
 [4 1 3 2 0]
 [3 2 4 0 1]
 [3 2 0 4 1]
 [4 0 3 2 1]
 [3 2 0 1 4]
 [2 0 3 1 4]
 [4 3 2 0 1]
 [4 0 2 1 3]
 [4 0 1 2 3]
 [0 2 4 3 1]
 [3 4 2 0 1]
 [2 4 0 3 1]
 [4 2 0 3 1]
 [0 2 3 4 1]]


By combining collaborative filtering with association rule mining, we can leverage both user-specific preferences and item relationships to create a more robust recommendation system. Collaborative filtering provides personalized recommendations based on user behavior, while association rule mining uncovers hidden patterns and relationships between items. This hybrid approach can enhance recommendation quality and diversify the suggestions provided to users.

# Simple Combination

In [145]:
# combine collaborative filtering and association rules to recommend goods to users
def combine_recommendations(ar_recommendations, cf_recommendations, weight_cf=0.5, weight_ar=0.5):
    combined_scores = {}
    for item in cf_recommendations:
        combined_scores[item] = weight_cf * cf_recommendations[item]
    for item in ar_recommendations:
        if item in combined_scores:
            combined_scores[item] += weight_ar * ar_recommendations[item]
        else:
            combined_scores[item] = weight_ar * ar_recommendations[item]
            
    combined_sorted = sorted(combined_scores.items(), key=lambda x: x[1], reverse=True)
    print("combined_sorted: ", combined_sorted)
    return [item for item, score in combined_sorted]

In [146]:
# test combine_recommendations function
ar_recommendations = {'A': 0.5, 'B': 0.3, 'C': 0.2, 'E': 0.1}
cf_recommendations = {'A': 0.1, 'B': 0.2, 'C': 0.3, 'D': 0.9}
combine_recommendations(ar_recommendations, cf_recommendations, 0.5, 0.5)

combined_sorted:  [('D', 0.45), ('A', 0.3), ('B', 0.25), ('C', 0.25), ('E', 0.05)]


['D', 'A', 'B', 'C', 'E']

# Genetic algorithm

In [147]:
# use genetic algorithm to generate recommendations
import random

# define the fitness function
def fitness(recommendations, transaction_matrix):
    fitness = 0
    for (user_idx, good_idx), interest in recommendations.items():
        if transaction_matrix[user_idx, good_idx] == 0:
            fitness += interest
    return fitness

# define the genetic algorithm
def genetic_algorithm(transaction_matrix, num_generations, population_size, mutation_rate):
    # apply UV decomposition
    U, V = uv_decomposition(transaction_matrix, best_k, 0.1, 0.1)

    # calculate the interest of users in goods
    user_ratings = np.dot(U, V)

    # generate recommendations using the interest matrix
    def generate_recommendations(user_ratings):
        recommendations = {}
        for user_idx, user_interest in enumerate(user_ratings):
            for good_idx, interest in enumerate(user_interest):
                if transaction_matrix[user_idx, good_idx] == 0:
                    # print("user_idx: ", user_idx, "good_idx: ", good_idx, "interest: ", interest)
                    recommendations[(user_idx, good_idx)] = interest
        return recommendations

    # generate recommendations
    recommendations = generate_recommendations(user_ratings)

    # initialize the population
    population = []
    for _ in range(population_size):
        chromosome = [random.choice([0, 1]) for _ in range(transaction_matrix.shape[0] * transaction_matrix.shape[1])]
        population.append(chromosome)

    # evolve the population
    for generation in range(num_generations):
        # evaluate the fitness of each chromosome
        fitnesses = []
        for chromosome in population:
            recommendations = {}
            for i, value in enumerate(chromosome):
                user_idx = i // transaction_matrix.shape[1]
                item_idx = i % transaction_matrix.shape[1]
                if value == 1:
                    recommendations[(user_idx, item_idx)] = user_ratings[user_idx, item_idx]
            fitnesses.append(fitness(recommendations, transaction_matrix))

        # select the top chromosomes
        top_population = [population[i] for i in np.argsort(fitnesses)[-population_size:]]

        # create the next generation
        new_population = []
        for _ in range(population_size):
            parent1 = top_population[-2]
            parent2 = top_population[-1]
            # parent1 = random.choice(top_population)
            # parent2 = random.choice(top_population)
            child = []
            for i in range(len(parent1)):
                if random.random() < mutation_rate:
                    child.append(random.choice([parent1[i], parent2[i]]))
                else:
                    child.append(parent1[i])
            new_population.append(child)
        population = new_population

    return population

In [148]:
top_population = genetic_algorithm(df_transactions, 100, 10, 0.5)
print(top_population[0])

[1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1]


In [149]:
# apply the genetic algorithm
for chromosome in top_population:
    recommendations = {}
    for i, value in enumerate(chromosome):
        user_idx = i // df_transactions.shape[1]
        item_idx = i % df_transactions.shape[1]
        if value == 1:
            recommendations[(user_idx, item_idx)] = user_ratings[user_idx, item_idx]
    print("Recommendations:")
    print(recommendations)
    print("Fitness:")
    print(fitness(recommendations, df_transactions))
# print(top_population[0])

Recommendations:
{(0, 0): 0.8402463120176149, (0, 2): 0.8562580660671386, (0, 3): 0.8052055050825025, (1, 3): 0.8992464126118265, (2, 1): 0.8782779706690906, (2, 2): 0.9128634519762175, (2, 4): 1.0348062546827081, (3, 1): 0.8007236228822322, (3, 2): 0.8385469000876652, (3, 3): 0.7890936005411111, (4, 0): 0.8947339702903621, (4, 3): 0.8909009437725928, (4, 4): 1.0431017201725594, (5, 0): 0.979503878611084, (5, 2): 0.9727989621779844, (5, 3): 0.9538152207224752, (5, 4): 1.0507772587356903, (6, 2): 0.9213369261766083, (6, 3): 0.9239871529510042, (6, 4): 0.9887760122067759, (8, 0): 0.9327208205443149, (8, 1): 0.9200808883686201, (8, 2): 0.9590766469754998, (9, 0): 0.9511038484173219, (9, 3): 0.9209289435958858, (9, 4): 1.0937283219511855, (10, 0): 0.8775554718120259, (10, 1): 0.8166740147082813, (10, 2): 0.9142447013088061, (10, 4): 0.8051056308381521, (11, 1): 0.8944240526115339, (12, 2): 0.9714085794960481, (12, 3): 0.9939854871443686, (12, 4): 1.028142569843205, (13, 0): 0.9668113322915

# References