In [1]:
# import task2 code which contains task1 code
# %run task2.ipynb

# Data preparation

In [2]:
# fake 20 transactions data with A, B, C, D, E
# A, B, C, D, E are 5 different products
transactions = [
    ['A', 'B', 'C'],
    ['A', 'C', 'D'],
    ['B', 'D'],
    ['A', 'B', 'C', 'E'],
    ['A', 'C', 'D'],
    ['B', 'D'],
    ['A', 'B', 'C'],
    ['A', 'C', 'D', 'E'],
    ['B', 'D'],
    ['A', 'B', 'C'],
    ['A', 'C', 'D'],
    ['B', 'D', 'E'],
    ['A', 'B', 'C'],
    ['A', 'C', 'D'],
    ['B', 'D'],
    ['A', 'B', 'C'],
    ['A', 'C', 'E'],
    ['B', 'D'],
    ['A', 'E', 'C'],
    ['A', 'C', 'D'],
]

# Association pattern mining

In [3]:
# use FP-Growth algorithm to generate association rules
from mlxtend.frequent_patterns import fpgrowth, association_rules
import pandas as pd

# convert transactions to one-hot encoded DataFrame
df = pd.DataFrame(transactions)
df = pd.get_dummies(df.unstack()).groupby(level=1).sum()

# apply FP-Growth algorithm
frequent_itemsets = fpgrowth(df, min_support=0.2, use_colnames=True)

# generate association rules
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.8)
rules

/Users/wzx/anaconda3/envs/mbd/lib/python3.9/site-packages/mlxtend/frequent_patterns/fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(


antecedents consequents  antecedent support  consequent support  support   
0          (C)         (A)                0.70                 0.7      0.7  \
1          (A)         (C)                0.70                 0.7      0.7   
2       (C, B)         (A)                0.30                 0.7      0.3   
3       (A, B)         (C)                0.30                 0.7      0.3   
4       (C, D)         (A)                0.30                 0.7      0.3   
5       (D, A)         (C)                0.30                 0.7      0.3   
6          (E)         (A)                0.25                 0.7      0.2   
7          (E)         (C)                0.25                 0.7      0.2   
8       (C, E)         (A)                0.20                 0.7      0.2   
9       (E, A)         (C)                0.20                 0.7      0.2   
10         (E)      (C, A)                0.25                 0.7      0.2   

    confidence      lift  leverage  conviction  zhangs_metric  
0          1.0  1.428571     0.210         inf       1.000000  
1          1.0  1.428571     0.210         inf       1.000000  
2          1.0  1.428571     0.090         inf       0.428571  
3          1.0  1.428571     0.090         inf       0.428571  
4          1.0  1.428571     0.090         inf       0.428571  
5          1.0  1.428571     0.090         inf       0.428571  
6          0.8  1.142857     0.025         1.5       0.166667  
7          0.8  1.142857     0.025         1.5       0.166667  
8          1.0  1.428571     0.060         inf       0.375000  
9          1.0  1.428571     0.060         inf       0.375000  
10         0.8  1.142857     0.025         1.5       0.166667

In [4]:
# use the apriori function to find frequent itemsets
# !pip install apyori 
from apyori import apriori

frequent_itemsets = apriori(transactions, min_support=0.2, min_confidence=0.8, min_lift=1, min_length=2)

# Extract and print the details
extracted_data = []

for record in frequent_itemsets:
    support = record.support
    for ordered_stat in record.ordered_statistics:
        items_base = ordered_stat.items_base
        items_add = ordered_stat.items_add
        confidence = ordered_stat.confidence
        lift = ordered_stat.lift
        extracted_data.append((items_base, items_add, support, confidence, lift))

# save it to dataframe
df = pd.DataFrame(extracted_data, columns=['items base', 'items add', 'support', 'confidence', 'lift'])
df

items base items add  support  confidence      lift
0         (A)       (C)      0.7         1.0  1.428571
1         (C)       (A)      0.7         1.0  1.428571
2         (E)       (A)      0.2         0.8  1.142857
3         (E)       (C)      0.2         0.8  1.142857
4      (A, B)       (C)      0.3         1.0  1.428571
5      (C, B)       (A)      0.3         1.0  1.428571
6      (D, A)       (C)      0.3         1.0  1.428571
7      (C, D)       (A)      0.3         1.0  1.428571
8         (E)    (C, A)      0.2         0.8  1.142857
9      (E, A)       (C)      0.2         1.0  1.428571
10     (C, E)       (A)      0.2         1.0  1.428571

# Collaborative filtering

In [6]:
import numpy as np
# convert transactions to one-hot encoded DataFrame
df = pd.DataFrame(transactions)
df_transactions = pd.get_dummies(df.unstack()).groupby(level=1).sum()
df_transactions = np.array(df_transactions)
df_transactions

array([[1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 1],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 1],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0]])

In [7]:
df_transactions.shape

(20, 5)

In [8]:
def uv_decomposition(R, k, learning_rate, regularization):
    """
    Performs UV decomposition on the input matrix R, with a target rank of k, using stochastic gradient descent (SGD).
    Returns the decomposed matrices U and V.
    """
    # Initialize U and V with random values
    num_users, num_items = R.shape
    U = np.random.rand(num_users, k) #num users by k
    V = np.random.rand(k, num_items) #k by num items

    # Perform stochastic gradient descent to optimize U and V
    for epoch in range(10):
        for i in range(num_users):
            for j in range(num_items):
                if R[i, j] > 0:
                    error = R[i, j] - np.dot(U[i, :], V[:, j])
                    U[i, :] += learning_rate * (error * V[:, j] - regularization * U[i, :])
                    V[:, j] += learning_rate * (error * U[i, :] - regularization * V[:, j])

    # Return the decomposed matrices U and V
    return U, V

In [9]:
# pick the bset K for UV decomposition
def calculate_rmse(R, U, V):
    predicted_R = np.dot(U, V)
    error = R - predicted_R
    error = error[R > 0]  # Only consider known values
    return np.sqrt(np.mean(error**2))

# Split the data into training and validation sets

best_k = None
best_rmse = float('inf')

for k in range(1, 10):
    U, V = uv_decomposition(df_transactions, k, 0.1, 0.1)
    rmse = calculate_rmse(df_transactions, U, V)
    print(f"k={k}, RMSE={rmse}")
    if rmse < best_rmse:
        best_rmse = rmse
        best_k = k

print(f"Best k: {best_k} with RMSE: {best_rmse}")

k=1, RMSE=0.11474179545212189
k=2, RMSE=0.11184606357812223
k=3, RMSE=0.1051062091540784
k=4, RMSE=0.10029067391681976
k=5, RMSE=0.09254868121933364
k=6, RMSE=0.09830612260859062
k=7, RMSE=0.08788687659779898
k=8, RMSE=0.09531428647780332
k=9, RMSE=0.09169308987107162
Best k: 7 with RMSE: 0.08788687659779898


In [10]:
# perform UV decomposition on the user-good matrix
U, V = uv_decomposition(df_transactions, best_k, 0.1, 0.1)

# calculate the interest of users in goods
user_ratings = np.dot(U, V)

# print("Original user-good matrix:")
# print(df_transactions)
print("user_ratings:")
print(user_ratings)

user_ratings:
[[0.93144117 0.87852882 0.90330233 0.91931842 0.93646307]
 [0.86053331 0.85053617 0.83067531 0.87899244 0.70477796]
 [0.81668299 0.90380745 0.86174289 0.8823343  0.92044881]
 [0.9108352  0.86885116 0.88367061 0.89598789 0.85775985]
 [0.93024148 0.91346291 0.93685954 0.88159623 0.96118548]
 [0.84038603 0.93049737 0.89670965 0.9705709  1.03424707]
 [0.93901721 0.94169894 0.94855358 1.02386431 0.89821393]
 [0.85152027 0.8334908  0.85212936 0.91054634 0.94097555]
 [0.93796419 0.91607313 0.87629771 0.93132406 0.97446135]
 [0.87928013 0.94157954 0.89977598 0.84248983 0.87843595]
 [0.93882272 0.95379373 0.95976204 0.90958679 1.06098882]
 [0.85939215 0.85863574 0.85311539 0.87858274 0.87859243]
 [0.91693322 0.95480643 0.91232705 0.9408652  0.93006211]
 [0.91809851 0.95993152 0.94455678 0.9511074  1.01170338]
 [0.86631322 0.90818958 0.90204605 0.93015626 0.9819513 ]
 [0.91829861 0.92241681 0.93928078 0.89117129 0.92433851]
 [0.93580403 0.94749301 0.93133235 0.98459691 0.92097304]


remove bought items

In [11]:
# get the recommendation order for each user
print(np.argsort(-user_ratings))

[[4 0 3 2 1]
 [3 0 1 2 4]
 [4 1 3 2 0]
 [0 3 2 1 4]
 [4 2 0 1 3]
 [4 3 1 2 0]
 [3 2 1 0 4]
 [4 3 2 0 1]
 [4 0 3 1 2]
 [1 2 0 4 3]
 [4 2 1 0 3]
 [4 3 0 1 2]
 [1 3 4 0 2]
 [4 1 3 2 0]
 [4 3 1 2 0]
 [2 4 1 0 3]
 [3 1 0 2 4]
 [3 1 4 0 2]
 [4 1 2 0 3]
 [4 0 3 2 1]]


By combining collaborative filtering with association rule mining, we can leverage both user-specific preferences and item relationships to create a more robust recommendation system. Collaborative filtering provides personalized recommendations based on user behavior, while association rule mining uncovers hidden patterns and relationships between items. This hybrid approach can enhance recommendation quality and diversify the suggestions provided to users.

# Simple Combination

In [12]:
# combine collaborative filtering and association rules to recommend goods to users
def combine_recommendations(ar_recommendations, cf_recommendations, weight_cf=0.5, weight_ar=0.5):
    combined_scores = {}
    for item in cf_recommendations:
        combined_scores[item] = weight_cf * cf_recommendations[item]
    for item in ar_recommendations:
        if item in combined_scores:
            combined_scores[item] += weight_ar * ar_recommendations[item]
        else:
            combined_scores[item] = weight_ar * ar_recommendations[item]
            
    combined_sorted = sorted(combined_scores.items(), key=lambda x: x[1], reverse=True)
    print("combined_sorted: ", combined_sorted)
    return [item for item, score in combined_sorted]

In [16]:
# test combine_recommendations function
ar_recommendations = {'A': 0.5, 'B': 0.3, 'C': 0.2}
cf_recommendations = {'A': 0.1, 'B': 0.2, 'C': 0.3, 'D': 0.9}
combine_recommendations(ar_recommendations, cf_recommendations, 0.5, 0.5)

combined_sorted:  [('D', 0.45), ('A', 0.3), ('B', 0.25), ('C', 0.25)]


['D', 'A', 'B', 'C']

# Genetic algorithm

In [17]:
# use genetic algorithm to generate recommendations
import random

# define the genetic algorithm
def genetic_algorithm(transaction_matrix, num_generations, population_size, mutation_rate):
    # apply UV decomposition
    U, V = uv_decomposition(transaction_matrix, best_k, 0.1, 0.1)

    # calculate the interest of users in goods
    user_ratings = np.dot(U, V)

    # generate recommendations using the interest matrix
    def generate_recommendations(user_ratings):
        recommendations = {}
        for user_idx, user_interest in enumerate(user_ratings):
            for good_idx, interest in enumerate(user_interest):
                if transaction_matrix[user_idx, good_idx] == 0:
                    recommendations[(user_idx, good_idx)] = interest
        return recommendations

    # generate recommendations
    recommendations = generate_recommendations(user_ratings)

    # define the fitness function
    def fitness(recommendations, user_good):
        fitness = 0
        for (user_idx, good_idx), interest in recommendations.items():
            if user_good[user_idx, good_idx] == 0:
                fitness += interest
        return fitness

    # initialize the population
    population = []
    for _ in range(population_size):
        chromosome = [random.choice([0, 1]) for _ in range(transaction_matrix.shape[0] * transaction_matrix.shape[1])]
        population.append(chromosome)

    # evolve the population
    for generation in range(num_generations):
        # evaluate the fitness of each chromosome
        fitnesses = []
        for chromosome in population:
            recommendations = {}
            for i, value in enumerate(chromosome):
                user_idx = i // transaction_matrix.shape[1]
                good_idx = i % transaction_matrix.shape[1]
                if value == 1:
                    recommendations[(user_idx, good_idx)] = user_ratings[user_idx, good_idx]
            fitnesses.append(fitness(recommendations, transaction_matrix))

        # select the top chromosomes
        top_population = [population[i] for i in np.argsort(fitnesses)[-population_size:]]

        # create the next generation
        new_population = []
        for _ in range(population_size):
            parent1 = random.choice(top_population)
            parent2 = random.choice(top_population)
            child = []
            for i in range(len(parent1)):
                if random.random() < mutation_rate:
                    child.append(random.choice([parent1[i], parent2[i]]))
                else:
                    child.append(parent1[i])
            new_population.append(child)
        population = new_population

    return population

In [18]:
# apply the genetic algorithm
top_population = genetic_algorithm(df_transactions, 100, 10, 0.1)
print(top_population[0])

[0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1]
